# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. We will try and get back to you as soon as possible.
  Please make sure you have given us as much context as possible.
  
  :laughing:
pullRequestOpened: >
  Thank you for raising the pull request. We will review it as soon as possible.
  
  To ensure document quality, we have enabled the CI test, which currently includes spell and format checks.
  If your pull request fails to pass the spell check, but you are sure that the word(s) is/are correct, feel free to add the word(s) into our glossary [.spelling](https://github.com/servicemesher/trans/blob/master/.spelling).
  :laughing: